### ISSUE TITLE
Working with objects

### ISSUE THREAD

**Issue by richstandbrook** [ecrmnn/collect.js#106] opened 2017-06-21 13:04 UTC
Just checking about the "wrapper for working with arrays and **objects**". Is this implemented yet? It's just when I pass in an object and try and use many of the functions: `transform`, `map`, `pop` etc. then it fails as it is trying to call the corresponding methods on `this.items` assuming that it is an array.

Am I doing something wrong or can I just not use objects in collect.js?

Brilliant library otherwise 👍

**Comment by g-plane** [comment] 2017-06-21 14:19
You can use objects in collect.js, but not all methods support objects like `map` so far. These methods only support array.

**Comment by BrainMaestro** [comment] 2017-06-21 19:27
The issue is that PHP treats hashmaps and arrays as the same datastructure while they are different in JavaScript and basically everywhere else. Translating a PHP specific array library to JS will cause issues like you're having. No way around it really. Functions like `map` and `pop` do not really make sense on objects.

**Comment by ecrmnn** [comment] 2017-06-21 19:48
Open for PRs if there is a good way to do this 😄  Closing for now.

**Closed by ecrmnn** 2017-06-21 19:48 UTC
